# Generated by Django 5.0.2 on 2024-02-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_addrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='ingrediants',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='titel',
            field=models.CharField(max_length=250),
        ),
    ]
