# Generated by Django 5.0.2 on 2024-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_addrecipe_ingrediants_alter_addrecipe_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='step',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='titel',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
