# Generated by Django 5.0.2 on 2024-02-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_addrecipe_description_alter_addrecipe_step_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addrecipe',
        ),
    ]
