# Generated by Django 5.0.2 on 2024-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_addrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='title',
            field=models.TextField(),
        ),
    ]
