# Generated by Django 5.0.2 on 2024-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_addrecipe_steps_alter_addrecipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecipe',
            name='meals',
            field=models.CharField(blank=True, null=True),
        ),
    ]
