# Generated by Django 5.0.2 on 2024-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_addrecipe_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='photo',
            field=models.ImageField(null=True, upload_to='recipe_photos/'),
        ),
    ]
