# Generated by Django 5.0.2 on 2024-03-16 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.addrecipe'),
        ),
    ]
