# Generated by Django 5.0.2 on 2024-03-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_review_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/recipe_photos/'),
        ),
    ]
