# Generated by Django 5.0.2 on 2024-03-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_contectus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contectus',
            name='user',
        ),
        migrations.AlterField(
            model_name='contectus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contectus',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
