# Generated by Django 5.0.2 on 2024-03-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_contectus_user_alter_contectus_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContectUs',
            new_name='ContactUs',
        ),
    ]
