# Generated by Django 5.0.2 on 2024-03-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_rename_contectus_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
