# Generated by Django 5.0.2 on 2024-04-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save',
        ),
    ]
