# Generated by Django 5.0.2 on 2024-04-25 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
